@extends('masterlayoutauth') @section('content')
<?php if(!empty($expire)){ ?>
<div class="otp-error"> 
Wrong OTP 
</div>
<?php } ?>
<div class="container">
<div class="step-div row">
   <h1>{{trans('lang.Two Step Authentication') }}</h1>
    <!-- First time -->
        <?php if(!empty($url)){ ?>
    <div class="col-md-4">
	    <h3>1. {{trans('lang.Install') }}</h3>
		<p>{{trans('lang.To use two-factor authentication') }}</p>
        <p>*  {{trans('lang.Download the google Authenticator app in the App Store') }}</p>
        <div class="store-img">
        <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" > <img src="{{asset('/public/img/google-play-2.png')}}"></a><a href="https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8" ><img src="{{asset('/public/img/itune.png')}}"></a>
        </div>              
    </div>
    <div class="col-md-4">
	    <h3>2. {{trans('lang.Scan') }}</h3>
		<p>{{trans('lang.Open your aunthentication app and scan the code with camera on your phone.') }}</p>
        <img src="<?php echo $url;?>" >
    </div>
	<div class="col-md-4">
	    <h3>3. {{trans('lang.Confirm') }}</h3>
		<p> {{trans('lang.Enter the verification code generated by your authentication app.') }}</p>
	    <div class="otp_form">
            <form action="{{$website}}">
                 <div class="">
                  <!--- <label>Enter OTP</label>  -->       
                   <input  type="text"   name="otp" value=""> 
                   <input type="hidden" name="_token" value="{{ Session::token() }}"/>
                   <input  type="submit" value="{{ trans('lang.Submit') }}">  
                 </div>              
            </form> 
        </div>
	</div>
        <?php }else{ ?>

    <!-- Secondtime -->
	<div class="col-md-4">
	    <h3>1. {{ trans('lang.Install') }}</h3>	   
		<p><i class="fa fa-check-circle-o" aria-hidden="true"></i></p>
    </div>
    <div class="col-md-4">	
        <h3>2. {{ trans('lang.Scan') }}</h3>
        <p><i class="fa fa-check-circle-o" aria-hidden="true"></i></p>
	</div>
	<div class="col-md-4">	
		<h3>3. {{ trans('lang.Confirm') }}</h3>
		<p> {{ trans('lang.Enter the verification code generated by your authentication app.') }}</p>
	    <div class="otp_form margin-low">
            <form action="{{$website}}">
                 <div class="">
                  <!--- <label>Enter OTP</label>  -->       
                   <input  type="text"   name="otp" value=""> 
                   <input type="hidden" name="_token" value="{{ Session::token() }}"/>
                   <input  type="submit" value="{{ trans('lang.Submit') }}">  
                 </div>              
            </form> 
        </div>		 
	</div>
    <!-- Second time end -->
        <?php } ?>           
</div>
</div>
@endsection
